config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get  '/about',   to: 'static_pages#about'
  get  '/login',   to: 'static_pages#login'
  get  '/profile',   to: 'static_pages#profile'
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates :title, presence: true, length: { minimum: 5 }
    validates :text, presence: true, length: {minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_helper.rb
module ApplicationHelper

  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def index
        @articles = Article.all
    end
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        byebug
        
        if @article.save
            byebug
            redirect_to @article
        else
            render 'new'
        end
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        
        if @article. update(article_params)
            redirect_to @article
        else
            reder 'edit'
        end
    end 
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        
        redirect_to articles_path
    end
    
    def show
        @article = Article.find(params[:id])
    end
end



private
    def article_params
        params.require(:article).permit(:title, :text)
    end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create 
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    
    private
     def comment_params
        params.require(:comment).permit(:commenter, :body)
     end
end

app/controllers/editprofile_controller.rb
class EditprofileController < ApplicationController
    def new
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
  

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editprofile_helper.rb
module EditprofileHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<% render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New Article' , new_article_path %>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
    </tr>
    
    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show' , article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy',
                                    article_path(article),
                                    method:  :delete,
                                    data: {confirm: 'Are you sure?' } %></td>
        </tr>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%=render 'form' %>

<%= link_to "Back" , articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Article List', articles_path %>

app/views/editprofile/new.html.erb
<h1> Welcome ya dumb ho</h1>

app/views/layouts/_header.html.erb
<header class="header">
    
<p class="header">
  ITCS 3155 PROJECT
  <span>
    UNCC BLOG
  </span>
  &mdash; GROUP 12 &mdash;
</p>
 
      <div class="topnav">
         <%= link_to "HOME", root_path, :class => current_class?(root_path)  %>
         <%= link_to "ABOUT", about_path, :class => current_class?(about_path)  %>
         <%= link_to "PROFILE", profile_path, :class => current_class?(profile_path)  %>
         <%= link_to "LOGIN OR REGISTER", login_path, :class => current_class?(login_path)  %>
         <input type="text" placeholder="Search...">
      </div>
</header>
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/....html.erb
<h1>StaticPages#...</h1>
<p>Find me in app/views/static_pages/....html.erb</p>

app/views/static_pages/about.html.erb
<html>
   <div>
       <body>
           <br><div class="box3"><center>
               <p>ABOUT TEMPLATE</p>
           </center></div>
       </body>
   </div>
</html>

app/views/static_pages/index.html.erb
<html>
   <div>
   <header>

   </header>
   <body>
      <center>
         <br>
         <div class="clearfix">
            <div class="box1">
               <p>Welcome to our UNCC Blog made by Group 12 consisting of Duke Le, Soam, Kevin Tran, and Glenn Um.</p>
               <img style='height: 100%; width: 100%; object-fit: contain' src="https://inside.uncc.edu/sites/inside.uncc.edu/files/fields/news_features/detail_image/bonner-leaders-360px.jpg">
            </div>
            <div class="box2">
               <h1><u>TRENDING</u></h1>
            </div>
         </div>
         
         <br>
         <div class="clearfix">
            <div class="box">
               <p><a href="#" class="button">LOGIN</a>
               <a href="#" class="button">REGISTER</a></p>
            </div>
            <div class="box">
               <p><a href="#" class="button">CREATE A NEW ARTICLE</a></p>
            </div>
            <div class="box">
               <p><a href="#" class="button">VIEW FEED</a></p>
            </div>
      </center>
   </body>
   </div>
</html>

app/views/static_pages/login.html.erb
<html>
   <div>
       <body>
           <br><div class="box3"><center>
               <p>LOGIN TEMPLATE</p>
           </center></div>
       </body>
   </div>
</html>

app/views/static_pages/profile.html.erb
<html>
   <div>
       <body>
           <br><div class="box3"><center>
               <p>PROFILE TEMPLATE</p>
           </center></div>
       </body>
   </div>
</html>

app/views/welcome/index.html.erb
<html>
   <div>
   <header>
      <p1><center>
  ITCS 3155 PROJECT
  <span>
    UNCC BLOG
  </span>
  &mdash; GROUP 12 &mdash;      </center>
</p1>
 
      <div class="topnav">
         <a class="active" href="#home">HOME</a>
         <a href="#about">ABOUT</a>
         <a href="#contact">PROFILE</a>
         <a href="#">SIGN-UP OR LOGIN</a>
         <input type="text" placeholder="Search...">
      </div>
   </header>
   <body>
      <center>
         <br><br>
         <div class="clearfix">
            <div class="box1" style="background-color:#212121">
               <p>Welcome to our UNCC Blog made by Group 12 consisting of Duke Le, Soam, Kevin Tran, and Glenn Um.</p>
               <img style='height: 100%; width: 100%; object-fit: contain' src="https://inside.uncc.edu/sites/inside.uncc.edu/files/fields/news_features/detail_image/bonner-leaders-360px.jpg">
            </div>
            <div class="box2" style="background-color:#212121">
               <h1><u>TRENDING</u></h1>
            </div>
         </div>
         
         <br>
         <div class="clearfix">
            <div class="box" style="background-color:#212121">
               <p><a href="#" class="button">LOGIN</a>
               <a href="#" class="button">REGISTER</a></p>
            </div>
            <div class="box" style="background-color:#212121">
               <p><a href="#" class="button">CREATE A NEW ARTICLE</a></p>
            </div>
            <div class="box" style="background-color:#212121">
               <p><a href="#" class="button">VIEW FEED</a></p>
            </div>
      </center>
   </body>
   </div>
</html>